### ISSUE TITLE
uSync import speed varies significantly among similar environments.

### ISSUE THREAD

**Issue by kcharecki** [KevinJump/uSync8#124]
**Describe the bug**
We have a couple of environments. All of them share the same specification - 16gb ram, 2.4Ghz 4 core, SSD. 
On freshly installed Umbraco instance, we run the imports. On some of the machines, the content (around 2k elements) is imported within 7 minutes or so. And on the others, it takes over an hour!

We've checked the build options, re-created the repository so basically, we are running the same app, just on a different machine and face significantly different results. 

The thing that I found that differs is the **%userprofile%\AppData\Local\Temp\UmbracoData** catalogue. On "faster" machines this folder is swelling whereas, on the slower, it remains at ~8mb. But I'm not sure that it is connected.

**To Reproduce**
1. Create ~1k content and media elements to be imported on machine A
2. Go to uSync section and click Full Import
1. Get the same elements and import on machine B
3. The same data is imported significantly slower on one of the machines.

**Expected behavior**
Consistent import time, without significant differences.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser Chrome 
 - Version 83.0.4103

**Comment by KevinJump** [comment]
😞 -  that really doesn't sound good at all. 

I will have to do some performance testing, nothing is immediately coming to mind that might make it different based on the folders 😕 

Any other differences between the sites, are both in 'sync' - as in a report returns zero changes ? wondering if the longer one is because it thinks there are differences between them all. The import mechanism first does a much faster check of exported xml files before doing changes, the changes are slower because they dig into the database and save items.

Also are databases the same ? SQLCE is way slower than SQL the time differences can be quite significant.

**Comment by kcharecki** [comment]
> 😞 - that really doesn't sound good at all.
> 
> I will have to do some performance testing, nothing is immediately coming to mind that might make it different based on the folders 😕
> 
> Any other differences between the sites, are both in 'sync' - as in a report returns zero changes ? wondering if the longer one is because it thinks there are differences between them all. The import mechanism first does a much faster check of exported xml files before doing changes, the changes are slower because they dig into the database and save items.
> 
> Also are databases the same ? SQLCE is way slower than SQL the time differences can be quite significant.

Hey, thanks for the response!

Yes, all of the envs use SQL db. 
We drop the databases, launch a new install of Umbraco instance. Then we do full-import. 
Our code-base, usync.config etc. are exactly the same.

And what is interesting is that first run of the import is slower too...

**Comment by KevinJump** [comment]
:( if you can it would be good to get a copy of the uSync/v8 folder. (usync@jumoo.co.uk) would help us in running real world perf tests.

**Comment by kcharecki** [comment]
> :( if you can it would be good to get a copy of the uSync/v8 folder. ([usync@jumoo.co.uk](mailto:usync@jumoo.co.uk)) would help us in running real world perf tests.

I'm afraid that I'd be forced to animize the data and currently I don't have time available for it.

Basically half of the content consists of two image properties and a grid layout's JSON. 
The rest is a .config for media - only images. 

I've checked the behaviour after deploying the app to Azure, and it is slow in there too. 
And what is even more interesting, the nucache.db doesn't exist in D\local\Temp\UmbracoData.

**Comment by KevinJump** [comment]
Some initial figures from internal testing : 

> Umbraco v8.6.3 (note post v8.4 there will be lookup improvements, as we don't need to do double content lookups anymore.)
> uSync / Content Edition v8.6.3
>  _(1111 content Items upto 4 levels deep & approx 132 media items - total 1284 items in sync)_ 
> [ Windows 10 64-Bit /  Intel i5-9400 (2.9GHz), 16GB,  SSD ]


### MSSQL Express DB

Action | Standard | AspNetTemp | EnvironmentTemp 
--------|-----------|----------| ---------------
First Import (all changes) | 102,322,s (102sec)| 101,232ms (101sec) |  101,960ms (101sec)
Export | 21,263ms (21.2 sec) | 22,589ms (22sec) | 22,583ms (22sec)
Import (no pending changes) | 12,588ms (12.7 sec)  | 13.101ms (13sec) | 13.111ms (13sec)
Report (no pending changes) | 12,542ms  (7.5sec) | 12.342ms (12.3sec) | 12.162 (12.1sec)

### SQLCE (local disk db file)

Action | Standard
--------|------
First Import (all changes) | 823,694ms (~ 13 mins)
Export | 122,374ms ( 2m 2sec)
Import (no pending changes) | 65635ms (65sec)
Report (no pending changes) | 65991ms (66sec) 

* All times are from a cold boot - repeat (cached) times are quicker because the Umbraco services cache lookups, looking at times for that we gain approx 6 seconds from that. e.g a full import on cached takes 84sec v 90sec with MSSQL DB.

Note: 
- MSSQL is way faster than SQLCE (like 8-9 times)
- The difference between report and export (10 secs above) - is disk speed, a report does an export (to memory) for the compare.

So things it could be 
- Database / connection speed - this makes the biggest difference in these tests
- Any third party / extra controls, I have tested a fairly basic, GRID/RTE control setup here, if there are more complex things going on, there is always a chance we have an issue inside the value mappers for those properties. 
- Umbraco version ? - I know for certain that pre 8.4 caching/lookup etc, inside Umbraco 8 wasn't ideal, that could cause issues with putting so much content in so quickly. 
- Disk access - So there are two bits of disk access going on when all this happens. 
   1. every publish will update the nucache.db file (i think) - so for azure you want this in EnvironmentTemp - as that is the quickest place for it
  2. uSync is reading files from uSync\v8 now i "think" you can move this too into app_data and it might well move to environmentTemp, again speeding it up for azure, but i am not 100% sure about that. 

so main questions are: 
- what version of Umbraco / uSync are you using.
- what if any 'fancy' things are you doing in these content items.

**Comment by KevinJump** [comment]
We have done some more experimentation for the next release and i think we have gotten content/media imports to be approx 20% faster (so 70sec  v 100sec for the above SQL Import) - Still can't get significant differences through changing paths though :(
