### ISSUE TITLE
No error is reported if a datatype is missing

### ISSUE THREAD

**Issue by Myster** [KevinJump/uSync8#143]
Given a DataType synchronised by a file called ControlsTest.config
When I deployed the website I had a bug in my cleanup that deleted *test.config files.
When the import ran it failed to add the datatype (no way uSyunc would know something went wrong)
When the import ran it ALSO failed to import properties using that datatype. (uSync should have known)
Then I expected there should be an error for the properties that failed to import.
However I got no indication it failed, except when I ran it again it still had the same properties to import.

 - Umbraco Version: 8.6.3
 - uSync Version:8.6.3
 - OS: Microsoft Windows Server 2016 Standard
 - Browser: Chrome

**Comment by KevinJump** [comment]
there is two parts to this, the easy part is reporting when the content item doesn't have the resultant property (done in 0f6aae24c4032c49eb0dc8e7511790d607fc5c30) 

The slightly more complex part is reporting when the datatype definition can't be found during the content type creation, so that part will likey not make the 8.6.4 release.

**Comment by KevinJump** [comment]
Closing this one, as the patch now handles the first issue - created new issue for next release to be better at the rest of it.
