### ISSUE TITLE
Content edition sync import does not respect content heirarchy & duplicates documents

### ISSUE THREAD

**Issue by westaj** [KevinJump/uSync8#15]
**Describe the bug**
When importing content with ContentEdition, parent ids and the content heirarchy are not respected. All content is important at the root level and the ids of the imported content are reset. Also, the documents are imported every time an import is run, resulting in duplicates. Please see screenshot.

**To Reproduce**
1. Export content with a heirarchy
2. Import into another instance

**Expected behavior**
Would be great if there was a way to import/respect the content heirarchy.

**Screenshots**
![Annotation 2019-04-23 101832](https://user-images.githubusercontent.com/34691/56598203-4e5f5c80-65b1-11e9-851c-d679b70f4cb8.jpg)

**Comment by Phil-Ouimet** [comment]
We've noticed the same issue. 
If we create the content on developer workstation A and then import them on workstation B it creates the new contents with completely new Guids. Since the parents do not exist for these contents they all appear at the root. 
If we export these content on workstation B then import them on the same machine the duplicates issue no longer appears. 
Is there a previous beta version for content edition we could use that would not have this issue?

**Comment by westaj** [comment]
I took a quick look at the source code and this scenario is supported. So I think this is just a bug, and probably something simple. I'm not proficient enough with Umbraco yet to debug a plugin, but this may motivate me :)

Hoping Kevin will comment soon, but if not I'll see if I can work out how to debug and then see if I can work out a patch.

**Comment by Phil-Ouimet** [comment]
Hi @westaj I also took a look debugging the code last night.
From what I can see in the ContentSerializer & ContentSerializerBase classes they seem to attempt to always find any existing content by its Guid.
It then it  fall back to trying to get it by locating its parent by their owns Guid and then looking for a child with the same alias. 
Since the content at the root does not exist and the code I see won't able to find it by any other means than the its guid importing a completely new branch of content would not be supported. 
I see that we may be able to use  entityService.GetRootEntities(UmbracoObjectTypes.ROOT);
to get the list of root nodes in that case, and under the assumption that someone would not create duplicate aliases at the root we may be able to address the issue.

**Comment by KevinJump** [comment]
Hi, 

yeah its almost certainly a bug like that Phil - in the old 'v7' version - we use to also store a path to the content (so it would be like "home/blog/my post") and then if everything else failed we would try to find it by the path, i suspect we need to migrate something like this across. 

it's also probable that the ordering is off, again we use to do this by folder structure so the parent nodes would always get created before we went into a child folder to create the next node, In theory, we now do this by the level attribute, so level 0 gets created before level 1 - if that isn't working then the parent nodes will be missing and everything will be flat :( 

Will take a look at this today - see if i can make more sense of it.

**Comment by KevinJump** [comment]
Looks to be fixed, will roll up into the next beta (Monday 29th 🤞 )

**Comment by westaj** [comment]
Fantastic! Thank you for your hard work!

--
Aaron J. West
403.999.3301

On Apr 26, 2019, at 10:18 AM, Kevin Jump <notifications@github.com<mailto:notifications@github.com>> wrote:


Looks to be fixed, will roll up into the next beta (Monday 29th 🤞 )

**Comment by KevinJump** [comment]
fixed in beta5 - https://github.com/KevinJump/uSync8/releases/tag/v8-beta5
