### ISSUE TITLE
Latest uSync reorders <Variations> and so reports changes on all content types

### ISSUE THREAD

**Issue by lesley-w** [KevinJump/uSync8#172]
**Describe the bug**
Latest version of uSync (v8.7.1) reorders "Variations" in IContentType xml

**To Reproduce**

1. Run uSync report in v8.7.0
2. No changes reported
3. Install uSync v8.7.1
4. Run uSync report in v8.7.1

All content types report "IContentType xml is diffrent - but properties may not have changed"
Only changes is order of "Variations" 

**Expected behavior**
xml generated should be in the same order as v8.7.0

**Screenshots**
![image](https://user-images.githubusercontent.com/23325280/95277106-83489780-08a9-11eb-8059-ea5054acc1eb.png)

**Desktop (please complete the following information):**
 - Umbraco Version: 8.6.4
 - uSync Version: 8.7.1

**Comment by KevinJump** [comment]
oh you see that is really annoying, I did that while fixing an issue where the file format gave loads of false positives if you upgraded from Umbraco 8.6 (the two new properties messed things up!).

We might be releasing 8.7.2 quickly (because since yesterday we've done some performance work, and gotten the content sync much faster) - If we do end up doing it soon then we will revert it - its a bit - now its out fixing it will cause as much of an issue the other way.

**Comment by KevinJump** [comment]
We didn't back port in the end, because we changed other stuff in later versions which changed the format anyway. so it would have broken later releases for no real benefit.
