### ISSUE TITLE
Merge after rename lost changes

### ISSUE THREAD

**Issue by Myster** [KevinJump/uSync8#185]
Hi,
I had a merge fail when I renamed a content type in one branch, and someone else edited it in another.
I renamed a content type wich generated old-name.config to new-name.config files.
someone in another branch edited old-name.config
When we merged the edit to old-name.config was overwritten by the <Empty ... change="Rename" /> element.

I wonder if we can 'not' have the mostly empty old-name.config file containing <Empty ... change="Rename" />
I think this file caused Git to not recognise the old-name.config -> new-name.config as a rename.
I believe?!?!  this would allow git to do a better job of resolving these two changes, it should detect the file was renamed, and then merge the change and rename together?

I could be wrong, and I don't understand why the old-name.config file exists. could it's role be filled some other way to allow git to recognise re-names?
Cheers.
Murray.

**Comment by KevinJump** [comment]
Hi 

The rename files exist to tell uSync that you have renamed a file (and to stop deployed sites from getting multiple items installed).

It is to cater for two scenarios : 

1. If you rename a doctype, then the empty file will be a rename, so when the files are imported onto a new site, uSync will know to rename the doctype to the new name - _now most of the time this doesn't actually happen because doctypes are probably already synced by key so they are found by key and the rename happens without the file._ 

2. Delete / new : 
if you delete a doctype. you will get an empty 'delete' file, 
but if you then create a new doctype with the same name as the one you deleted the empty file will be changed to a 'rename' file.

then when you come to sync this change onto another site. 
- uSync will see that you have a rename in the folder, and the existing item will be renamed to the new one.
- the new import file will be imported - but because the rename has happened it will find the doctype by alias, and update its values.

this helps us stop a delete/recreate which can cause Umbraco to clear out content data 😞 

## It also helps people with deployments:
In v7 We did use to remove the old files on a delete or rename, but we found that it caused people issues when deploying their sites. a lot of standard deployment methods don't delete existing files on the target server - so the sync got confused because the old files where still there and people where getting duplicates. 

All of this is because the default convention we use in uSync is to name the files with the name of the doctype - so when the doctype is renamed the file name changes - you can stop this by chaning uSync to use `GuidNames `setting.

**If you change the to `GuidNames` setting - then renames don't change the file names, so you don't actually need any of this hoop jumping that we do to cope with it (the deletes still do create the empty files - because we need to know when to remove things).**
