### ISSUE TITLE
Include CSS / Scripts

### ISSUE THREAD

**Issue by AaronSadlerUK** [KevinJump/uSync8#186]
As the CSS, Scripts can be changed from the backoffice.

Could these be added as options to be included in the export

**Comment by KevinJump** [comment]
Hi, 

We actually took CSS/Scripts out in i think v7.6 because they no longer have any database elements.

our scope is - uSync syncs the database bits to disk - so the direct serialization of these files is beyond that.

having said that if you wanted to include them in the usync folder - you have two options.

1. Write the handlers to control the serialization of the files to the usync folder - handlers can be plugged in with no alteration to the core (this is how content edition and uSync.Vendr work). 
2. hook into the uSynService.ExportComplete event, to copy the files when an export is done. and the ImportComplete event to copy them the other way.

The first way is the 'usync way' if you want them to behave exactly like all the other files but if i was doing it i would do 2.
-  have a component that hooks into the save events for scripts/template that copies the files to usync/v8/files or some such.
- have the component also hook into the ExportComplete event and copy the folders when someone does an export
- also hook into ImportComplete and copy the files the other way when someone does an import.

**Comment by AaronSadlerUK** [comment]
Ok thanks @KevinJump I will look into that
