### ISSUE TITLE
Unknown provider

### ISSUE THREAD

**Issue by fpeeetraDeeev** [KevinJump/uSync8#223]
**Describe the bug**
The dashboard does not load correctly after updating to latest version.
As always, works locally but not in production mode/server.
**To Reproduce**
Uninstalled usync through nuget package manager in VS.
Removed lost files and folder that still exist
Installed latest version v8.9.1.0 through nuget
Browsning to dashboard interface

**Screenshots**
![aaasdfasdf](https://user-images.githubusercontent.com/60224478/116412282-d0388f00-a836-11eb-83f5-e0686fa0a11b.PNG)

**About your Site (please complete the following information):**
 - Umbraco Version: 8.13.0
 - uSync Version: v8.9.1.0
 
**Additional context**
Result of exception output:
Error: [$injector:unpr] Unknown provider: uSync8DashboardServiceProvider <- uSync8DashboardService <- uSyncSettingsDashboardController

I´ve tried to remove all the usync files and folder from in prod env and uploaded them manually from local env without any success. Is this a common issue? Anyone know how to move forward from this? Where is the service provider located uSync8DashboardServiceProvider ? Cant find it in the solution.

**Comment by KevinJump** [comment]
Hi, 

Have you incremented your client dependency version ? (in settings/clientdependency.config) - sometimes the javascript is cached by umbraco and this can cause issues after an update.

**Comment by fpeeetraDeeev** [comment]
Hi, thanks for the quick response. Impressive! 
No so i tried it now by increasing it to a random higher number without any success.

**Comment by KevinJump** [comment]
:( 

what happens if you click on the Reference "v" is not defined and then expand the javacript (click on the `{}` icon under the file 
![image](https://user-images.githubusercontent.com/431231/116414991-e6dbe780-a830-11eb-961b-dc346e02a91a.png) )

this hopefulyl will expand the script to show where the error is. 

the error might not be in uSync at all. when on production Umbraco merges all the javascript files, and if there is something else wrong further up it can cause issues latter on in the file -

I am just installing new test site to confirm we haven't broken something somewhere.

**Comment by fpeeetraDeeev** [comment]
True! This has absolutely nothing to do with usync at all. Another plugin which was load before usync was not initialized correctly.
Many thanks

**Comment by KevinJump** [comment]
No worries. 

Iif you have any control over the code, i would recommend wrapping it in a function like we do for the uSync controllers. (see https://github.com/KevinJump/uSync8/blob/v8/8.7-main/uSync8.BackOffice/App_Plugins/uSync8/changeDialogController.js) this just isolates any errors in the code to that block and they don't then impact other things in the compressed file)
