### ISSUE TITLE
Changing and deleting datatypes occur in the wrong order causing data loss

### ISSUE THREAD

**Issue by Myster** [KevinJump/uSync8#238]
**Description**
I changed a Nested content picker (any datatype) to a more permissive one, and deleted the old one.
When this change was imported on a new server/DB the datatype and the property using it were deleted first.
Then the property with the new datatype was re-created, and it was empty!

**To Reproduce**
1. Create "simple RTE test" datatype
2. Add property called "test" using "simple RTE test" datatype to a Doctype (save)
2. Edit an instance of that Doctype such that the RTE contains text "This is here"
3. Save and publish
4. backup the DB
4. Edit the doctype, and change "simple RTE test" to "full RTE" (save and close)
5. (at this point a usync config is updated)
5. Observe "This is here" content remains.
6. delete "simple RTE test" datatype
7. (at this point usync marks a deleted datatype)
8. restore the DB you backed up
9. touch web.config to restart
10. click uSync Impot
11. Observe "This is here" isn't, it's gone!

**Expected behavior**
"This is here" should still be there.

**About your Site**
 - Umbraco Version: 8.10.1
 - uSync Version: 8.9.1.0
 - Browser: chrome

**Additional context**
The issue AFAIK is the datatype is deleted first, thus deleting the property and it's data 

**Screenshots**
Here's screenshots from a more complicated example using nested content datatype rather than the RTE:
![report](https://user-images.githubusercontent.com/354777/118901452-6c057880-b967-11eb-82aa-11930505438a.png)
![log](https://user-images.githubusercontent.com/354777/118901455-6d36a580-b967-11eb-90d9-b53ee7ee3c8e.png)

**Comment by Myster** [comment]
Moving the datatype deletions to the end of the process should fix this?

**Comment by KevinJump** [comment]
I am trying to get my head around what i think is a simple solution (just need to write some of it down - to sanity check).

if when we delete an item we set the file's `level` to a high number (e.g 9999) then the sort process which happens during an import will automatically make deletes happen at the end.  I just need to work through the remifactions of this. 

1. DataTypes - leaving deletes until the end will indeed cause no issues as they are at the bottom of the pile
2. Doc/Media/Member Types: if we create everything then delete, it should be OK, because if someone does delete a doctype and then recreates / renames a new one with the same name we "should" overwrite the existing one. 
3. Content/Media - deleting at the end shouldn't cause an issue, again the clashes should be fixed.

but: we do need to consider what happens when using the "guid filenames" setting and deletes.

OK - so up until #216 - we didn't run the clean up, on guid save/moves which would have meant there could be a delete with the same name as an existing item (with a different guid). but #216 fixes that !  - so it should clear the way for the deletes 

In Content/Media the method for finding is slightly different, because if you delete something in "folder a", then rename something in "folder b" and then copy that back into the "folder b" the sum total of that is a rename - and we need to track it. 

I think we need a slightly more in-depth `DoesItMatch` method in the content handlers for this to be something, alongside guid key matching, we need to do path matching -but if we do that then the level = 9999 should be OK.

**Comment by KevinJump** [comment]
Tidy up this is in since v8.9.6
