### ISSUE TITLE
Export (v8) does not remove existing files/folder

### ISSUE THREAD

**Issue by JoseMarcenaro** [KevinJump/uSync8#26]
Hi. 
When exporting configs, the existing folders and files are not removed.  I'm using Umbraco v8.0.2 and uSync release version (8.0.0)

**Steps to reproduce: files not removed**
1) Export
2) Delete a document type
3) Export again
The deleted document type remains on disk

**Steps to reproduce: folders not removed**
1) Create a folder in Document Types and create a Document Type inside
2) Export
3) Rename the folder
4) Export again
The new folder is serialized and the old one stays on disk, - the doc.type definition is duplicated.
Running the Report action shows the definition needs to be Updated..

**Comment by KevinJump** [comment]
Hi 

uSync8 will not completely remove the files when a delete happens, instead, it creates an 'empty' file which allows us to mark the item as deleted or renamed, this has a number of advantages over the 'action file' method of v7 - firstly it lets deletes happen inline with other actions, and its good for people deploying usync as they don't have to have scripts cleaning folders before deployment. 

i will check the folder one, it should do the same thing (this time marking the empty file as a 'rename') but will double check that works. 
and you might get a update message because of this, we need to check that

**Comment by JoseMarcenaro** [comment]
Oh, I didn't realize it was a marker file. Thanks for explaining, it sounds like a great solution for the deletions.

Regarding renaming a folder, it is an edge case.. but it might happen so let me know if you find a fix.
Thanks!!

**Comment by KevinJump** [comment]
just cleaning up - this was released v8.0.1 (so a while ago)
