### ISSUE TITLE
Error when importing templates: The template '.cshtml' file is missing.

### ISSUE THREAD

**Issue by Marko-Tukic** [KevinJump/uSync8#265]
**Describe the bug**
When importing templates, i get  The template '.cshtml' file is missing. Happens on Linux docker container on Linux docker host when importing. 

**To Reproduce**
1. On Windows create template in Umbraco 9 - Master.cshtml
2. Try importing on Linux system

**Expected behavior**
Template should be imported

**About your Site (please complete the following information):**
 - Umbraco Version: 9.0.0-rc001
 - uSync Version: 9.0.0-rc001
 - Browser chrome

**Additional context**
Probably happens because of case sensitive environment.

**Comment by vsilvar** [comment]
@KevinJump Somewhat related to this issue, when using Compiled views:
```
<PropertyGroup>
    <RazorCompileOnBuild>true</RazorCompileOnBuild>
    <RazorCompileOnPublish>true</RazorCompileOnPublish>
</PropertyGroup>
```

You stop having the ability to import any templates, as the files no longer exist in disk but in a dll.

Might be worth to either completely remove the check or at least have the option to disable it.

**Comment by KevinJump** [comment]
yeah (with the missing template) the issue might be that if you tell Umbraco to create a new template (when the entry is missing in the db) and you don't pass it the content of the file - it wipes what ever is one disk :( 

that is certainly the v8 behaviour - so i will do some tests and see what happens if we remove the loading from v9 (i would rather we did really - because then we don't have to find the file at all).

**Comment by Marko-Tukic** [comment]
If i name everything conected to template with lowercase - for example master and master.cshtml there is no problem and template is imported.
