### ISSUE TITLE
Import Sort Order

### ISSUE THREAD

**Issue by marcloveUSN** [KevinJump/uSync8#282]
When running imports that include ContentType changes I have noticed that the sort order on properties is not always correct. Running the import a second time seems to solve the issue.

**Comment by KevinJump** [comment]
I think we have inadvertly fixed this, in 9.3 we import on both level and sort order (previously we imported on level and set sort order when creating the item). 

I think the setting of a sort order on create doesn't work (because Umbraco ignores it) - but when we then import new things in order- the order is as expected  (mostly, if for some reason you have rouge sort orders they may not be 100% on first import)
