### ISSUE TITLE
License in database

### ISSUE THREAD

**Issue by marklonquist** [KevinJump/uSync8#315]
**Is your feature request related to a problem? Please describe.**
We just migrated to Umbraco 9 and we're running our setup in GCP in Kubernetes.
We don't want to store our license file in our repositories for security reasons.

**Describe the solution you'd like**
Store license information in the db like so many other things is now.

**Describe alternatives you've considered**
Create a license.json file rather than the current XML data. This would make it possible to have it served easily from secret files in kubernetes (or other secret data stores like HashiCorp Vault).

Other solution would be to make it available programatically so we could create it on startup with data from appsettings (again, injected from secret files).

**Comment by KevinJump** [comment]
Hi, 

yes we can look into having the licence fallback from somewhere else. at the moment we are following the same practice as the core umbraco team who store the forms licences is the same folder - so we sort of jumped into the same location.

sadly the one thing its quite hard to do with Umbraco in its current form is add additional configuration sources without changing the program.cs (and as plugin we don't want to do that). otherwise we could quite quickly have a source and then things like key vaults would just work.

but i am sure we can do something... will have a think and play.

**Comment by KevinJump** [comment]
OK, For the next release. we will attempt to get the key and domains from the config first: 

```json
"uSync" : {
  "Complete": {
      "License": {
        "Key": "Key",
        "Domains":  "Domains.com"
      }
  }
}
```

this will then let you store these config values in any configured config source and not within the repo. 

- does this sound right ?

**Comment by marklonquist** [comment]
Sounds perfect!

**Comment by KevinJump** [comment]
closing here - tracking on uSync.Complete repo. 

The next full patch release is sometime off (likely after Christmas) we will release a nightly next week with this feature in it - if you want to test it.
