### ISSUE TITLE
baseUrl in uSync 9

### ISSUE THREAD

**Issue by marklonquist** [KevinJump/uSync8#316]
Hi

How do I go about setting the "baseUrl" in uSync9? I found this post on umbraco forums;
https://our.umbraco.com/packages/developer-tools/usync/usynccomplete/101025-issue-publishing-when-using-https

but doesn't seem to be present in any option files in the uSync namespaces.

Also, we are hosting in GCP with a SSL terminating LB in front of our umbraco instance. So I wonder how I even figure out what baseUrl I should set 😄 

The service binds itself on http://localhost:5000

**Comment by KevinJump** [comment]
Hi, 

Yeah we haven't surfaced the setting in the UI (we probably should).  but it is still there 

settings are now stored in the DB in the `[uSyncPublisherServerConfig]` table, and that has a baseUrl column for each server.
if you set the base URL in the table then it will be used (you might have to restart the site once you have set the value in the DB)

**Comment by marklonquist** [comment]
Ah okay. Must admit I didn’t check the table for it because it seemed to be in the app settings according to the docs; http://usync.jumoo.co.uk/docs/complete/publisher/config

at the very bottom. 😜 though it isn’t showed in the json example. 🤔

Thanks for the info! Will have to try it tomorrow.

**Comment by marklonquist** [comment]
Alright so I've been doing some testing.

This is the server i'm trying to reach from local:
<img width="822" alt="Screenshot 2021-11-21 at 19 47 30" src="https://user-images.githubusercontent.com/1456819/142775074-a4299626-b147-4464-b51c-6b3c1914d1f5.png">

As you can see, it has one URL in the address field, and another on the page. This is the one behind an SSL terminating LB.

Then, in my local DB, i've added a baseUrl:
![Screenshot 2021-11-21 at 19 49 42](https://user-images.githubusercontent.com/1456819/142775107-66f50c07-431d-493b-9d6c-97ea4f283901.png)

But it is not working. What am I doing wrong? 😄 Still getting Unauthorized response.

**Comment by marklonquist** [comment]
Blanked out some parts for security reasons.

**Comment by marklonquist** [comment]
Seems there might be a bug in your HMACHandler.cs file. It tries to get the "syncPublishServer" obj from DB, but when trying to fetch it from the database, the URL is specified as;
`https://bt-olympus-content-svc.XXXXXXXXX.com/umbraco/uSyncReceive/uSyncReceiveApi/Enabled`

this means it fails to get the correct data from the db, as the URL in there is just;
`https://bt-olympus-content-svc.XXXXXXXXX.com/umbraco`

But your code specifies that it should "start with":
```
public SyncPublishServer GetByUrl(string url) => this.GetServers().FirstOrDefault<SyncPublishServer>((Func<SyncPublishServer, bool>) (x => x.Url.InvariantStartsWith(url)));
```
which is never true with the above URL. So it ends up using the "GetDefaultServer" code.

Perhaps it should be the other way around?
```
public SyncPublishServer GetByUrl(string url) => this.GetServers().FirstOrDefault<SyncPublishServer>((Func<SyncPublishServer, bool>) (x => url.InvariantStartsWith(x.Url)));
```

**Comment by KevinJump** [comment]
Hi, 

yes, also there is a bit of code we didn't port over from v8 around finding things based on baseURLs (in another bit).

Fixed this for the next release and pushed a beta to our nightly feed : 

- https://dev.azure.com/jumoo/Public/_packaging?_a=package&feed=nightly&package=uSync.Complete&protocolType=NuGet&version=9.0.5-beta001

(instructions on how to add the feed to your builds are on the [connect to feed](https://dev.azure.com/jumoo/Public/_packaging?_a=connect&feed=nightly) tab at the top)

## Added Include host option

We've also added the **IncludeHost** option which exists in v8. - by default this is set to true, so when we sign a request the URL includes the host value (e.g `http://www.somesite.com/umbraco/uSyncReceive/uSyncReceiveApi/Enabled`) but if we set the **IncludeHost** value to false then requests are signed with just the path and query (`/umbraco/uSyncReceive/uSyncReceiveApi/Enabled`).

This means you don't have to worry about the host value, _(in theory it means requests intended for another server could be replayed onto this server, This is still unlikely as the attacker would need to be intercepting the requests from one server that was using the same AppID/AppKey pair -  and then sending them to the target. )_

with the latest next release (and latest beta - see below) you can set IncludeHost on the appsettings.json file (**n.b all servers will need to have this set if it is used, because both sender and receiver need to agree on the format of the request**)

```json
"uSync": {
    "Publisher": {
      "Settings": {
        "IncomingEnabled": true,
        "AppId": "XXXXXXXXXXXXX",
        "AppKey": "XXXXXXXXXXXXXX",
        "IncludeHost": false
      }
    }
}
```

**Comment by KevinJump** [comment]
this also adds the ability to set base host in the UI. (you might need to refresh js files/cache.)

under the 'advanced' tab of a server : 

![image](https://user-images.githubusercontent.com/431231/142842764-c5591b08-7d6d-4163-8407-d953735efd5a.png)

**Comment by marklonquist** [comment]
Nice.

I used the IncludeHost = false method as I believe the AppId and AppKey should be enough. :-)
