### ISSUE TITLE
Back Office "view appsettings" doesn't show all set appsettings.

### ISSUE THREAD

**Issue by mistyn8** [KevinJump/uSync8#329]
v9.0.6

![image](https://user-images.githubusercontent.com/12418214/148571254-4899968c-c433-49ec-9f0f-a89a9212e423.png)

Not sure if the intention is to show where appsettings has altered from the default, or all the settings currently in play defaults as well?

**Comment by KevinJump** [comment]
yeah to be honest i was a little unsure about this change - it is only showing changes, but if you have defaults then yeah they go, its hard / impossible to tell i think that is actually set (because app-settings can be in several places). 

I might well go back to the old , here are all your settings view.

**Comment by KevinJump** [comment]
also that view doesn't work properly ! 

V9.1 is a UI release to wlll fix it all in that
