### ISSUE TITLE
Usync import will fail if you swap aliases of 2 document types

### ISSUE THREAD

**Issue by bielu** [KevinJump/uSync8#343]
**Describe the bug**
As described in title if you swap aliases of document types usync will fail on import.

**To Reproduce**
1. Create to document types, as example: Document (document) and Document Item (documentItem)
2. Change Document alias to document2
3. Change Document Item alias to document
4. Change Document alias to documentItem
**Expected behavior**
A usync is making import without failing

**Screenshots**

**About your Site (please complete the following information):**
 - Umbraco Version: 9.1.2
 - uSync Version: 9.0.6
 - Browser [e.g. chrome, safari] N/A

**Comment by KevinJump** [comment]
Hi, 

Yeah I think its the same issue that means you have to give them a temp name when you do it, e.g. the names clash. 

We can probably do something where we give them a temp name and then in the second pass give them the proper one.

**Comment by bielu** [comment]
@KevinJump yeah I think it has to be resolved in that way 👍

**Comment by KevinJump** [comment]
the PR should fix this - i want to put some performance checking around it, because it not going to be the quickest thing if you rename a doctype twice and it has a lot of content associated with it (when you save it Umbraco will update all the existing content and that can be slow). 

but its an edge case that i don't think will slow down most 'normal' uses so should be ok. 

RC version in our nightly builds if you want to test.

https://dev.azure.com/jumoo/Public/_packaging?_a=package&feed=nightly&package=uSync&protocolType=NuGet&version=9.1.1-rc001.20220211.1

**Comment by bielu** [comment]
@KevinJump I hope to have time to test that this thursday, I will let you know if I will find anything.
