### ISSUE TITLE
Error when importing templates: The template '.cshtml' file is missing. 

### ISSUE THREAD

**Issue by TQ-Benji** [KevinJump/uSync8#361]
**Describe the bug**
When importing templates, get error "The template '.cshtml' file is missing"
Could be related/similar to #265 and #308 don't see anything about them in change logs 

I have this config enabled so the views are in a dll not actual files
```
<PropertyGroup>
    <RazorCompileOnBuild>true</RazorCompileOnBuild>
    <RazorCompileOnPublish>true</RazorCompileOnPublish>
</PropertyGroup>
```

Workaround is to create the template on the deploy server with same name and then go into file system and delete the generated template .cshtml file so it uses the dll version. which if adding lots of new templates is not ideal over multiple environments

**To Reproduce**
Create a new template locally
deploy to server and run usync import
error appears for "The template '.cshtml' file is missing"

**Expected behavior**
Template imports

**About your Site (please complete the following information):**
 - Umbraco Version: 9.2.0
 - uSync Version: 9.1
 - Browser: Edge

**Additional context**
Template file names are saved as pascal case

**Comment by KevinJump** [comment]
Hi thanks for the prompt, you right this is something we need to look at, its been on our list for a while - we will bump it up!

**Comment by KevinJump** [comment]
Hi, 

Yeah the problem appears to be that Umbraco isn't aware that you are running with the razor compiled (i am not even sure if its possible to tell this at runtime). 

if you look at the template folder in Umbraco when running in this mode then all the templates will be there (because they are in the DB - but the files will be blank.

![image](https://user-images.githubusercontent.com/431231/159425799-448b5267-d00b-43c4-97f8-ffad8e205b96.png)

even in this mode. saving anything in the templates folder creates a file in views 

Internally - there isn't a way of createing a template in umbraco without that also setting content and saving something to disk (so the SaveTemplate methods all save something to disk 😞 ). 

I think we will probably have to write a config work around (because we can't tell if we are using compiled views). 

- where we do create the template (as now) 
- but then delete the file if a config value is set.

**Comment by KevinJump** [comment]
So we have some code that might work for this : 98a5c002a54cd9f737fc488f38e8180745ccfd65

This requires a setting to appsettings.json : 

```json
 "uSync": {
      "Sets": {
        "Default" : {
          "Handlers" : {
            "TemplateHandler" : {
              "Settings" : {
                "UsingRazorViews": true
              }
            }
          }
        }
      }
    }
```

Which tells uSync to do the following: 

1. when creating a template if the template file isn't on disk, assume its in a razor view and create the template anyway.
2. when finalizing the template delete the template file that Umbraco will have created (because umbraco doesn't know about the razor views) so that the template file from the compiled razor views is used. 

This is a little hacky (we are ineffect creating and then deleting the .cshtml file) but i don't think there is another way to do it because umbraco will always create the template file when we save a template. 

~**n.b if you for some reason have a mix of compiled and non-compiled template views this is probibly going to cause issues, because this will delete the template view on disk when it imports - thus deleting anything you might be using for a view that isn't inside the razor view.**~ (not if we tag the content of the view see below comment)

I have had a look at various APIs and services in aspnet core and i don't think there is a way for us to tell if a template exists in a razor view or on disk (other than looking for it on disk, but once umbraco has done something it is going to be on disk). 

Anyway going to test it a little bit see if this resolves the issue in a reliable way

**Comment by KevinJump** [comment]
Addition to this in 9d4d152c5639c749755586d3d341af172a0e2cc1

when we create the content for a file we know we are going to delete we add a marker to id, 

then later on in the process when we delete the item, we can check and confirm its a 'temp' view and delete the physical file. (little worried about file locking here, but reverted to the system io methods seems to make it not lock up.

**Comment by KevinJump** [comment]
THis change is in 9.3 - so in theory we now support compiled razor views with uSync

**Comment by leekelleher** [comment]
@KevinJump _(sorry to post on an old issue)._
Is it possible to set the `UsingRazorViews` option in code? e.g. from startup `.AdduSync()`
I'm exploring how it could work with FirstBoot 🥇🥾

**Comment by KevinJump** [comment]
Yes - you can do it in a post configure even in a composer . 

```cs
builder.Services.PostConfigure<uSyncHandlerSetSettings>("Default", options =>
{
     options.HandlerDefaults.AddSetting("UsingRazorViews", true);
});
```

**Comment by leekelleher** [comment]
Awesome, thanks @KevinJump!
It's one of those, once someone has shown you a hint of the code, it's like _Ahh, of course!_ 😀
