### ISSUE TITLE
My custom Set is not taken into account

### ISSUE THREAD

**Issue by Trobeloo** [KevinJump/uSync8#464]
Here is mys uSync 10.3.2 section in my Umbraco 10.3.2 appsettings
  
"uSync": {
    "Settings": {
      "RootFolder": "uSync/Import uSkinned 3.05",
      "DefaultSet": "**MySet**",
      "ImportAtStartup": "None",
      "ExportAtStartup": "None",
      "ExportOnSave": "All",
      "UiEnabledGroups": "All",
      "ReportDebug": false,
      "AddOnPing": true,
      "FailOnMissingParent": false,
      "CacheFolderKeys": true,
      "ShowVersionCheckWarning": true,
      "CustomMappings": {},
      "EnableHistory": true
    },
    "Sets": {
      "Default": {
        "Enabled": true,
        "HandlerGroups": [],
        "DisabledHandlers": [],
        "HandlerDefaults": {
          "Enabled": true,
          "Actions": [],
          "UseFlatStructure": true,
          "GuidNames": false,
          "FailOnMissingParent": false,
          "Group": "",
          "Settings": {}
        },
        "Handlers": {}
      },
      "**MySet**": {
        "Enabled": true,
        "HandlerGroups": [],
        "DisabledHandlers": [],
        "HandlerDefaults": {
          "Enabled": true,
          "Actions": [],
          "UseFlatStructure": false,
          "GuidNames": false,
          "FailOnMissingParent": false,
          "Group": "",
          "Settings": {}
        },
        "Handlers": {}
      }
    }
  }

The problem is that the MySet set is not used:
![image](https://user-images.githubusercontent.com/2814461/212493123-f9ed174e-aa84-4804-8eba-255b55a33f7a.png)

**Comment by KevinJump** [comment]
Hi, 

I think you have to have a bit of code to make a custom set readable. 

in a composer you need the following: 

```cs
var customSettingPath = "uSync:Sets:MySet";

builder.Services.Configure<uSyncHandlerSetSettings>("MySet",
    builder.Config.GetSection(customSettingPath));
```

this is because sets are loaded as [Named Options](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-7.0#named-options-support-using-iconfigurenamedoptions) and i haven't found a clean way of enumerating and auto loading them yet 

_These options groups can infact be anywhere, so they don't have to be in the uSync sets section you could have them in the root of the appsettings.json file. as long as the 'path' element in the above code points to the correct place the set should load._
