### ISSUE TITLE
uSync dashboard is not loading after an upgrade from v8 to v10

### ISSUE THREAD

**Issue by CarlSargunar** [KevinJump/uSync8#476]
Not sure how to best describe this issue, as to replicate it will require quite a few steps. I haven't yet tried on a clean v8 -> v10 upgrade, but I've noticed that on my v10 site I am not able to load the dashboard

![image](https://user-images.githubusercontent.com/6002765/221900977-0dd6ba05-de00-4284-9c92-2fba7d6d4761.png)

There were no entries in the log related to uSync, and nothing in the IIS log either, so not sure what futher information I can include in here to help diagnose or replicate the problem other than trying a clean install of v8 and upgrading it to v10.

**Comment by CarlSargunar** [comment]
If there are other things I can look at, happy to do so and add further information.

- Target framework set at .NET 6.0
- Version installed on server 6.0.14
- Umbraco version 10.4.0
- uSync version 10.3.2

**Comment by KevinJump** [comment]
Hi, when upgrading from v8 to v10 - you need to remove any usync files in `/app_plugins` as these are superceeded by the files in the Razor Class Library ? 

the build step should do this, but if you deploy, they won't necessarly be deleted ?

**Comment by CarlSargunar** [comment]
Yeah - I've checked those files aren't there, and I've even done a clean installation. The app_plugins contains contentment, as well as a few other files from plugins we've written ourselves, but uSync is definitely not there

**Comment by KevinJump** [comment]
are you running the v10 site in IIS or IIS Express ? 

I've seen file permissions being an issue, when running in IIS - asp.net will still attempt to get the files from the nuget cache (which lives in `c:\users\username\.nuget`) and by default it won't have permissions for that ?

**Comment by CarlSargunar** [comment]
Locally on IIS Express, and on our staging server on IIS, but it doesn't appear to be working on either. I will try clearing the nuget cache on the server, but not sure why it doesn't work on my local either.

**Comment by CarlSargunar** [comment]
Tried a nuget cache clear using 

`nuget locals all -clear`



App_plugins folder :
![image](https://user-images.githubusercontent.com/6002765/221928997-37836d04-4238-4a26-9679-38adab857d15.png)


Still seeing this. For ref, otehr packages are working
![image](https://user-images.githubusercontent.com/6002765/221928675-bb3ce81f-77c6-4759-9d0c-4ea444de787e.png)

**Comment by CarlSargunar** [comment]
Hey @KevinJump  - a bit further investigation into this, and it looks like it might be environmental, although I've absolutely no idea why

![image](https://user-images.githubusercontent.com/6002765/226378212-b2056fe2-488d-43f4-b04b-c9c4a88bf097.png)

The dashboard seems to load fine on my laptop (win 11, vs 2022, all the latest .NET SDKs installed) but NOT on my desktop (win 10, vs 2022, all the latest .NET SDKs installed) or on our staging server. 

All dev environments are using iis express, and staging is using full IIS, but other than that there really isn't anything that I can see of think of which might be different. 

I've even taken the db from my laptop, moved it to the desktop and tried that, but it still doesn't work on the desktop

Any ideas what we can look into further?

**Comment by KevinJump** [comment]
Its odd,

so when you are not on "local dev" (e.g visual studio/code) - are run running the results of a "dotnet publish" / publish profile. 
these should place the uSync files in `wwwroot/app_plugins/` so you should be able to see them on the disk.

- i suppose it could be caused case sensitive file systems, but unless you've done something funky on windows that isn't going to be an issue and besides we actually do test for that. and it works on Linux etc. 

if you are not doing the "publish" then it will be looking in the .nuget cache, is there files in there ? 

- Legacy files are still hanging around, does the site have an /app_plugins/usync folder (not in wwwroot) and is there a usync8.*.dll file or files in the bin folder (from the v8 version!) because that would cause problems i would guess.

**Comment by CarlSargunar** [comment]
Huh - learned something new today - I always assumed the app_plugins folder lived in the root, as that's where our in-house plugins worked from, as well as contentment, but I didn't realise it also picked up from wwwroot/app_plugins. I had assumed since the error reported that it was looking in /app_plugins/usync/backoffice/usync/dashboard.html (as per screenshot) that it would be from the root folder. 

On the working environment I can indeed see the static files in wwwroot/app_plugins - I'll check the other machine later and get back

**Comment by CarlSargunar** [comment]
OK - so testing on both machines, if I run the site through a dotnet publish, it works, but when I run it through visual studio, on a debug build on the desktop, it doesn't work, but DOES work on the laptop

So that's very confusing? What on earth could be different about a debug build within visual studio on one machine, that's not on the other machine?

Neither of these are running through IIS, I'm using the IIS Express in visual studio. Can't think what it could be

**Comment by CarlSargunar** [comment]
I've worked around is by using config to enable ImportAtStartup:All, which basically does the job on our staging server, but it's a workaround

Still no idea why:

- Running in Debug in VS doesn't work
- Publishing to a server has the same problem

To answer your earlier questions, locally I'm just using dotnet run, or running under debug in vs2022, and there's no leftover legacy files in the  /app_plugins/usync folder. Looking at /wwwroot/ app_plugins/usync and I can see all the files in there

![image](https://user-images.githubusercontent.com/6002765/227579801-6db137b6-d70a-4b07-bda3-6f4ee09b6238.png)

**Comment by KevinJump** [comment]
- When you run a dotnet publish - the package files are copied from `c:\users\username\.nuget\packages\` to your `.\website\wwwroot\app_plugins`

-when you run via visual studio (or dotnet run)
   - the files are not copied, there is a StaticFiles FileProdivder in the site (standard asp.net thing) that mapps the `c:\users\username\.nuget\packages\packagename\app_plugins\` folder to make it appear as if its in `wwwroot\app_plugins`

so i would suspect that mapping isn't working: 

## common prolblems (I've seen anyway) are. 

1. Permissions, for some reason the site running can't see the `%username%\.nuget\packages` folder so the files are not served (this is more common with IIS as that runs under a different user).
2. messed up cache, this is a lot less common and should also break the dotnet publish, but maybe clearning the nuget cache and rebuilding might help ( ` dotnet nuget locals -c all` ) - you will need to do a rebuild after this for your computer to refetch all of the files. 

## possible (but I've never seen this). 

- maybe you have something that is interfering in the Static Files element of asp.net? Umbraco has a line like `app.UseStaticFiles();` which turns this on. when you run a site in published mode. the razor files are turned off. 
- internally to Razor the static files are actually managed in a file in `obj\project.assets.json` maybe that's corruped (a dotnet clean, dotnet build should reset that)
- There might still be old files in "website\app_plugins" - if the site somehow still has the old target file reference these could be getting copied back everytime you debug/build ? 
- maybe there is a difference between debug and release ? - when you are doing a dotnet run its building it in debug (prob) and when you run via visual studio is it debug or release? (again this should work regardless, but it might explain why one works and the other doesn't)

to be honest most of this is guessing - it's odd, because we don't really see issues like this (beyond the running the site via IIS one.)  and usually its a quick fix. 

quite happy to have a quick call next week if you want to go over it, and we can see if there is anything we can spot.

**Comment by CarlSargunar** [comment]
Thanks for the fantastic explainations Kevin - In the end I managed to fix whatever it was that was broken by removing, re-insalling and running a full export, and also doing a full re-build of the publish profiles

I wish I could say which of those fixed it, but one of them did, and I changed too much to warrant going through and identifying but I definitely am better informed on how it all works

If you're happy, I'll close this issue now. Thanks
