### ISSUE TITLE
Media Handler doesn't migrate content references

### ISSUE THREAD

**Issue by jaandrews** [KevinJump/uSync8#478]
Media nodes list pages that reference them on their info tabs (see below)
![image-use](https://user-images.githubusercontent.com/5932368/223873929-da38e767-b9ae-4d8a-99f5-9c915860cec2.png)
Usync doesn't currently migrate this information, but it should as umbraco uses these connections to determine whether an image can safely be deleted.

**To Reproduce**
1. Add a media picker control to a doc type
2. Create a page with that doc type
3. Choose an image and save the page.
4. Check the image's info tab to confirm the connection was created.
5. Import the image into another environment.
6. Check the info tab there to see that missing information.

**Expected behavior**
The media connections are migrated when the media is imported.

**Screenshots**

**About your Site (please complete the following information):**
 - Umbraco Version: 10.4.0
 - uSync Version: 10.3.2
 - Browser: Chrome

**Comment by KevinJump** [comment]
Hi, 

This actually works for me 😢 **(just to clarify as in **i do** see the references after a sync)** 

Its actually a built in Umbraco thing that i don't think uSync needs to sync.

when a content item is saved, umbraco looks for the linked media in the content items (via property converters), and creates the relationships in the DB. 

uSync can sync relationships but doesn't sync these ones because they are driven by events in Umbraco. 

I think possible explanations might include that the content item was synced before the media item was imported (uSync does media before content by default, so this might have been over two different syncs). and in doing so the content item wasn't scanned for connected media - so the media item relationship wasn't synced? 

You can if you want - tell uSync to sync the relations (including the umbraco generated ones) - not sure what side effects this might have (it might be fine!). 

the default setting _(which is what happens when there is no config in an apssettings.json file)_ is below: 

removing "umbMedia, umbDocument" from the list would mean uSync would attempt to sync them. 

```json
"uSync" :{
    "Sets": {
        "Default": {
            "Handlers": {
                "RelationTypeHandler" : {
                    "Settings" : {
                        "Exclude": "relateParentDocumentOnDelete,relateParentMediaFolderOnDelete,relateDocumentOnCopy,umbMedia,umbDocument",
                    }
                }
            }
        }
    }
}
```

**Comment by jaandrews** [comment]
@KevinJump Thanks for the feedback. I'll double check things on my end and let you know if I find any problems.
