### ISSUE TITLE
Content pull/push via publisher ignores content type permissions

### ISSUE THREAD

**Issue by mayhammf** [KevinJump/uSync8#490]
**Describe the bug**
uSync publisher allows content to be pulled/pushed with disregard to content structure permissions

**To Reproduce**
1. Go to Remote Content in the content section
2. Drill down the content tree
3. Select content node within a parent that is not present in the target server
4. Click push 
5. Content is published in the target server under the closest existing ancestor  where it is not allowed to be present according the content type permissions. 

**Expected behavior**
Content should not be allowed to be pushed or pulled under a parent that does not allow for content of that type to be created.

**Screenshots**
N/A

**About your Site (please complete the following information):**
 - Umbraco Version: 10.4.1
 - uSync Version:  (current latest for Umb10)
	- uSync: 10.3.4
	- uSync.Complete: 10.4.1
	- uSync.Forms: 10.0.1
 - Browser Chrome 

**Additional context**
N/A

**Comment by KevinJump** [comment]
Hi, there are settings for some of this, and for the other bit, i think that is the way it has to work. 

You can stop uSync from creating the content in the closet ancestor when the parent is missing. 

there is a fail on missing parent setting (see https://docs.jumoo.co.uk/usync/reference/config) 

```json
{
    "uSync": {
        "Settings": {
            "FailOnMissingParent": true
        }
   }
}
```

This will cause uSync not to put the content under the nearest tree rather tell you it doesn't exist and fail. 

if you wanted you could turn on "Include Ancestors" in the uSync.Publisher server settings 
( https://docs.jumoo.co.uk/usync/complete/publisher/send#advanced ) 

Then the parent items would also be sent for sync along with the page you are sending. - this however is Off by default because it means changes in those pages are also pushed with the page so you would in effect be republishing your homepage 
each time, and we think most people probably don't want that. 

-
we don't obey the context structure rules when syncing because there are many packages and indeed practices that mean pages can be created underneath things programmatically when they shouldn't according to the rules. A good example is a search page or sitemap. its common for people to create these pages and then change the structure rules once they have done so to stop accidental creation of a second search or sitemap . uSync has to honour how people have set their site up - so we create these pages if they exist.

**Comment by mayhammf** [comment]
Thank you for the detailed response. I should have looked for that option in the docs before reporting an issue. 
Closing this.
