### ISSUE TITLE
Import fails on forms and content

### ISSUE THREAD

**Issue by craigs100** [KevinJump/uSync8#520]
**Describe the bug**
Umb 12.0.1, uSync 12.0.2 + FormsEdition 10.0.1.0
Import fails on Forms and Content when exported from the same versions.

More detail at https://discord.com/channels/869656431308189746/1129783774469705778/1129783774469705778

Full export from local dev site. V9 folder contents replaced on live site with new versions from local. All Settings import ok, Everything in Content imports ok except Content items. The home.config reports "Cannot save non-current version", after that, nothing has a parent so fails.  Forms fails completely with :-

"formsHandler": Import Failed : "System.TypeLoadException: Could not load type 'Umbraco.Forms.Core.Models.IFormEntity' from assembly 'Umbraco.Forms.Core, Version=12.0.0.0, Culture=neutral, PublicKeyToken=null'. at uSync.Forms.Services.SyncFormService.GetForm(Guid key) at uSync.Forms.Serializers.FormSerializer.FindItem(Guid key) at uSync.Forms.Serializers.FormSerializer.DeserializeCore(XElement node, SyncSerializerOptions options) at uSync.Core.Serialization.SyncSerializerRoot`1.Deserialize(XElement node, SyncSerializerOptions options) at uSync.BackOffice.SyncHandlers.SyncHandlerRoot`2.ImportElement(XElement node, String filename, HandlerSettings settings, uSyncImportOptions options)"

Sorry can't be more specific due to the state of the sites. Have tried this many times. Same results.

**Comment by craigs100** [comment]
Today have manage to do some decent testing. FormsEdition isn't ready for V12 as it's requirements are 10 && 11.  Also found Umb V11.4.2 reporting itself as 12.0.0 thus not allowing install of FormEdition. Re: https://github.com/umbraco/Umbraco-CMS/issues/14562. Having attempted to upgrade sites iaw latest umb security patch, am now reverting till this is all sorted out.

**Comment by KevinJump** [comment]
Hi, 

It looks like there are some minor breaking changes in Umbraco Forms for v12,. but @DG-Billy has[ created a PR for us](https://github.com/KevinJump/uSync.Forms/pull/11), so we just need to do some testing and then release a v12 version.

**Comment by craigs100** [comment]
Just for clarity, the V11.4.2 reporting as V12.0.0 was user error BUT uSync was implicated :)  Read on for details.....

https://github.com/umbraco/Umbraco-CMS/issues/14562#issuecomment-1637674605

**Comment by KevinJump** [comment]
Yes - we can't *really* stop you installing uSync v12 on v11 if you try hard enough  - _well we might be able to make harder, its something we can look at*._ 

Best recommendation is to add the version when adding the package 

you can wild card it, to the major. 

```
install package uSync --version 11.* 
```

We have a bit of pain here, because uSync is tracking Umbraco versions and in the main because uSync touches most of the Umbraco APIs we have to do this with majors because of breaking changes etc - So for clarity we try to do version matching. 

_* I think we might be able to do something with dependency ranges on the package but it will have to look into it a bit more - and even then i am not sure it will block all senarios where installing a later version doesn't bump the dependent package version too._

**Comment by craigs100** [comment]
If you want something breaking, I'm usually your man ;)  The interesting thing here was though that it looked like uSync had auto-upgraded the Umbraco installation.

**Comment by KevinJump** [comment]
uSync 12 depends on `Umbraco.Cms.Web.BackOffice` so for v12 that will be the v12.0.0 version, when you install it , that dependency will get added, guessing that what makes it report v12. 

Now in theory it should tell there is a clash when you add it, (because this is an implied dependency) and you will have another one from the "Umbraco.Cms" package, so they should clash, and it should warn you. but if i am honest i haven't read up on *ALL* the possibilities here, so it might be that works, but we might be able to make it not work - based on how we list our dependencies.

**Comment by KevinJump** [comment]
Hi,

version of forms for Umbraco 12 (uSync.Forms v12.0) is released now. 

https://www.nuget.org/packages/uSync.Forms/12.0.0
