### ISSUE TITLE
Roots feature - doesn't look in custom "Root folder"

### ISSUE THREAD

**Issue by NikRimington** [KevinJump/uSync8#587]
I have a site running Umbraco v13 with uSync configured with the setting "RootFolder" to be `uSync/v13` which for core usync behaviour all works fine. However, I recently updated to use the new Roots functionality as this site was from a "migrated database".

I had to import updated files and did the following:

1. Moved everything from the v13 folder to a root folder.
2. Re-migrated the source database with latest changes and put the new usync files into a v13 folder.
3. Set `lockRoot` as false to allow for existing types to be updated
4. Ran a uSync report

## What happened?
uSync reported no changes

## What did I expect to happen?
uSync to report the differences between the original files and the update uSync files

## Work around
In order to get this to work I had to set the "folders" property with `uSync/Root/` and `uSync/v13` - however I would have expected the report/import to have used the RootFolder value in combination with the Folders meaning I don't believe I should have needed to override the Folders value.

**Comment by KevinJump** [comment]
Hi, 

Yeah I can see what your saying. maybe we need to combine them all and remove duplicates, because i can see the case (and we built it for this) where you might have multiple roots (e.g a root1, root2 and a usync folder) and the folders merges them all together. 

I think we are suffering from the original folder setting always being called "rootfolder" in the settings :( which makes it a bit confusing, our plan is to phase it out completely and just use the "folders" settings.

**Comment by KevinJump** [comment]
was fixed in 13.1.1
