### ISSUE TITLE
[BUG] ConfigSyncApiSwaggerGenOptions overrides Umbraco behavior

### ISSUE THREAD

**Issue by senneclaeskens** [KevinJump/uSync8#629]
**Describe the bug**
https://github.com/KevinJump/uSync/blob/v14/dev/uSync.Backoffice.Management.Api/Configuration/ConfigSyncApiSwaggerGenOptions.cs#L21C9-L21C88

`options.CustomOperationIds(e => $"{e.ActionDescriptor.RouteValues["action"]}");`

This code overrides the default Umbraco implementation

https://github.com/umbraco/Umbraco-CMS/blob/v14/dev/src/Umbraco.Cms.Api.Common/Configuration/ConfigureUmbracoSwaggerGenOptions.cs#L46

`swaggerGenOptions.CustomOperationIds(description => _operationIdSelector.OperationId(description));`

**To Reproduce**
Upon installing the usync nuget, the umbraco behavior is overwritten because of the double CustomOperationIds.

**Expected behavior**
Implementation of OperationIdSelector, which would have them work both: https://docs.umbraco.com/umbraco-cms/reference/api-versioning-and-openapi#adding-custom-schema-ids

Upon checking, it might be better to use IOperationIdHandler, since otherwise, any custom logic might be skipped.

**Additional context**
Umbraco + usync 14.0.0-rc1

**Comment by KevinJump** [comment]
Thanks for this, i didn't spot that. 

but i am concerned the umbraco solution isn't sustainable for multiple packages 🤔 

If i implement a Custom `OperationIdSelector` that calls umbraco base selector. but then another package comes along and implements a custom operations selector that overrides the base, doesn't all my config get lost because my class is no longer registered?) .

It might just be that i only need to impliment something on my site i get the swagger from, because once the client is built it doesn't matter ?

I will raise this with someone in the core see what they say.

**Comment by senneclaeskens** [comment]
You are totally right about that, that's why I made an edit, suggesting IOperationIdHandler.

Basically, you can create a handler like this:

```
    public bool CanHandle(ApiDescription apiDescription)
    {
        if (apiDescription.ActionDescriptor is not ControllerActionDescriptor controllerActionDescriptor)
        {
            return false;
        }

        return CanHandle(apiDescription, controllerActionDescriptor);
    }
    
    public bool CanHandle(ApiDescription apiDescription, ControllerActionDescriptor controllerActionDescriptor)
        => controllerActionDescriptor.ControllerTypeInfo.Namespace?.StartsWith("uSync") is true;
    
    public string Handle(ApiDescription apiDescription)
    {
        // custom logic which returns the operationId
    }
```

Info taken from https://github.com/umbraco/Umbraco-CMS/pull/16062

**Comment by KevinJump** [comment]
thanks, I've added that - I think there is a RC2 of Umbraco on the horizon, so will merge a few things and hopefully release it all for that.

**Comment by KevinJump** [comment]
we did this, closing.
