### ISSUE TITLE
After a complete import, there is no content.

### ISSUE THREAD

**Issue by a-t-k** [KevinJump/uSync8#668]
**Describe the bug**
I'm importing into Umbraco v14 and uSync v14 a complete export from uSync v13. After the import is completed, I find nothing in 'Content'. However, in the log it's recorded: "Document <> (id=26699) has been published." In Media, the content is available. Also, document types with all fields are imported

**To Reproduce**
1. Export complete with uSync v13 and Umbraco v13
2. Create new instance of umbraco 14, empty db
3. start complete import with uSync v14  from export v13
4. in "Content" tab you see nothing

**Expected behavior**
All content is there.

**Screenshots**

**About your Site (please complete the following information):**
 - Umbraco Version: 14.2.0
 - uSync Version: 14.0.0
 - Browser [e.g. chrome, safari] chrome

**Additional context**
-

**Comment by KevinJump** [comment]
Hi,

yeah i think there are subtle diffrences in some of the properties between v13 and v14 that we haven't yet ironed out, it does work with basic things but some quick testing i can see i am getting warning about block lists, ( `[Umbraco.Cms.Core.Models.Blocks.BlockGridValue]' read too much or not enough.`) which i can tell you from experience is going to be a pain to debug :( .

Once that fails for something like the home page its a cascade failure, because without a homepage all the other pages won't appear or get published :( -

but its going to take some time to debug this i would think...

**Comment by KevinJump** [comment]
Hi, 

We did quite a bit of work in this for the v15 release which now has a lot more going on in terms of block list imports (it migrates from the v13/14 to v15 versions for a start).

 And i think its more robust and this doesn't happen (well certainly in the tests we had where it did happen it doesn't) any more
