### ISSUE TITLE
Umbraco Content Nodes being deleting after uSync import

### ISSUE THREAD

**Issue by OwainJ** [KevinJump/uSync8#84]
**Describe the bug**
We're having a weird issue where Content Nodes (and Umbraco grid properties) are getting deleted when we perform a uSync import on our Test deployment.

After we perform a uSync import, some content nodes disappear from the content tree, they seem to simply vanish, they don't appear in the recycle bin, they're just gone.

We've lost the home node (and all the content underneath) on our Test deployment from this issue, thankfully this isn't really an issue with test data, but on a production deployment, this could cause major problems.

**To Reproduce**
1. Update doctypes on Dev deployment.
2. Perform uSync export.
3. Push changes to Test deployment.
4. Perform uSync import on Test deployment. 
5. Check content nodes for changes.

I'm not sure if this is reproducible, or if we have stumbled upon some weird edge case.

**Expected behavior**
A uSync import should not be deleting content nodes when performing an import.

**Screenshots**
Here's a screenshot of the Umbraco logs showing the exceptions after a uSync import.
The exceptions start after the 'Running Import: "Macros"' task, where we start getting errors stating that our code cannot find the "SiteSettings" content node.
![image](https://user-images.githubusercontent.com/17008780/75547521-fb510400-5a22-11ea-9abb-412398c65e13.png)

**Desktop (please complete the following information):**
The import was triggered from a pc running:
 - OS: Windows 10
 - Browser Chrome
 - Version 80.0.3987.122

**Additional context**
Our dev and test environments are both hosted on Microsoft Azure, our dev server is an F1 and Test is an S1.
- Umbraco 8.5.1
- We have these uSync packages installed via nuget:
     - uSync
     - uSync.BackOffice.Core
     - uSync.Community.Contrib
     - uSync.ContentEdition
     - uSync.Core

**Comment by KevinJump** [comment]
Hi 

You might have some 'empty' config files in the folders which are markers for deletes and renames.

When you delete and item uSync writes a 'empty' `.config` file over the existing .config file for that item. this file tell uSync to delete the item (if it finds it) on the other site. It does this to capture the actions, but also because it reduces the risk of orphaned files lingering in the uSync folder when you deploy your site. 

An empty file looks like this 
```
<?xml version="1.0" encoding="utf-8"?>
<Empty Key="3bf2f7a4-8d5a-4ee7-b252-66c4231dca69" Alias="MyContent" Change="Delete" Level="1" />
```
It might be worth checking to see if you have any files with the <empty> key in your content. 

Deletes are only performed by key, so if it doesn't match the key, the item won't be deleted but its possible that's what has happened?

Nothing goes into the bin because the delete is a proper delete, if the item was in the recylce bin on the source site, then uSync would put it in the recycle bin on the target, but it thinks its a proper delete, so it's removing it. 

### Possible issues:
Just wondering about what might have gone wrong. when you re-create an item after deleting it - the empty file should be overwritten, its possible that didn't happen and you have ended up with a delete where there shouldn't be one (would be good to know if this has happened)?

### Next steps.

1. It would be good if you could send us a copy of the uSync/v8 folder if possible (usync@jumoo.co.uk) 
2. I would suggest to progress you delete the existing uSync/v8 folder and perform a full export, this will remove all <empty> commands from the sync and then see if that solves the issue.

**Comment by KevinJump** [comment]
Hi just to add, if you add the following to the serilog.config file you will actuall see the point at which uSync attempts a delete: 
```
<add key="serilog:minimum-level:override:uSync8" value="Debug" />
```

---- 
our delete code is here : https://github.com/KevinJump/uSync8/blob/3902f00937dc7d33586d927ad040e6ef55dcf7bf/uSync8.Core/Serialization/SyncSerializerBase.cs#L194-L218

Although the comment is a little misleading, because when a delete fails because it can't find a key, it calls the serializers, `FindItem(alias)` for the `ContentSerializer` This always returns null. (so it never finds the content another way). So only GUID based deletes are ever performed.

**Comment by OwainJ** [comment]
Hi Kevin,

Thanks for replying!

Unfortunately, I can't access the uSync folder on our Test deployment as our client is hosting it and won't give us access. 🙃 I've contacted them asking if they can send me a copy of the uSync folder, hopefully they'll get back to me soon. (although that will probably be Monday)

As the issue doesn't happen with our dev deployment I'm going to assume that our uSync folder in dev (which we do have access to!) is good. I've looked through it and I can't see any rouge delete configs. Although it might be a good idea for us to delete it and re-export just in case.

I know we have definitely renamed some doctypes over the course of development, I am wondering if there is a correlation between them and the content that was deleted, maybe some old delete/rename configs got leftover on the Test deployment.

I'll definitely apply that serilog config, so if it happens again we can see more info in the log, and I'll let you know as soon as they send me the uSync folder from the Test server!

Cheers,

Owain

**Comment by KevinJump** [comment]
OK, I'll keep an eye out for updates. 

A "clean the folder" button is something we have considered, we just need to have plenty of warning etc around it, just to make sure people don't do it by accident and loose the deletes they **do** want to happen.

**Comment by OwainJ** [comment]
Hi Kevin,

A "clean the folder" button would be great in our situation! Although I agree, it would need plenty of warnings around it and would probably only be needed in niche circumstances like ours.

Also, good news! Our client sent me a copy of the uSync/v8 folder from the test server and, upon looking through it, I noticed that it contained a lot more ContentType config files when compared to a fresh export from our dev environment. (89 ContentType config files compared to just 52 produced from a fresh export)

I decided to run a "report" on a copy of our Dev environment, using the config files from the Test server, and I noticed that some doctypes were duplicated and listed as both 'Delete' and 'Update'.

![image](https://user-images.githubusercontent.com/17008780/75677566-ad870680-5c83-11ea-9446-07cb095d7c33.png)
![image](https://user-images.githubusercontent.com/17008780/75686962-f85d4a00-5c94-11ea-8a4c-4cd98dd794a4.png)

The contentPageSettings and person .config files:
![image](https://user-images.githubusercontent.com/17008780/75689946-f944aa80-5c99-11ea-9b7d-90784bef3c0e.png)
![image](https://user-images.githubusercontent.com/17008780/75690270-72440200-5c9a-11ea-92d7-d5bbf5e1ad08.png)

When I ran an import, the content nodes that were duplicated in the report got deleted from the content tree  (including all 'person' nodes, and the 'contentPageSettings' node).
Although I couldn't see any delete actions logged in the Umbraco log. (The serilog config has been added)

![image](https://user-images.githubusercontent.com/17008780/75688814-0e203e80-5c98-11ea-940e-dcc1b7ee5ab1.png)
(The errors are the sql server timing out.)

The uSync post-import report shows the doctypes as both being deleted and created:

![image](https://user-images.githubusercontent.com/17008780/75689161-a1597400-5c98-11ea-9285-f77b7aefd0b7.png)

It looks like you were correct that leftover 'delete'/'rename' config files seem to be causing the issues. As exporting a fresh set of configs and then importing with them seems to work with no issues.

Now the question is, how did those files get leftover on our test deployment in the first place? I guess we will just have to be more careful when deploying in the future.

Maybe it would be a good idea to have uSync check for "bad"/conflicting configs prior to an import and warn if any are found? Would it even be possible to distinguish a "bad" set of configs from a "good" set? Or maybe it could check and then warn the user if the requested changes will cause any content in the content tree to be deleted?

Owain

**Comment by OwainJ** [comment]
Well, I think just solved how those configs got leftover!

Our dev server is hosted in Azure and when a pull request gets accepted and merged into the 'development' branch, it is automatically deployed onto the dev server.

And just now, I created a new branch, emptied the uSync/v8 folder, created a fresh export and pushed that up for a pull request into dev. Once it was merged and deployed, I decided to check the uSync folder on the dev deployment to make sure the configs were released correctly. And what do I see? 97 items in the ContentTypes folder instead of just 52... 

![image](https://user-images.githubusercontent.com/17008780/75696154-074af900-5ca3-11ea-8050-bbc2b2ee1978.png)
(Screenshot of my local development branch, compared to our dev deployment.)

It would appear that old config files are not being removed when we release an environment!

**Comment by OwainJ** [comment]
Just in case anyone else is also facing this issue, we solved it by enabling the _"Remove additional files at destination"_ and _"Exclude files from the App_Data folder"_ options on the _"Deploy Azure App Service"_ task in our Azure DevOps release pipeline. 

![image](https://user-images.githubusercontent.com/17008780/76200259-34d6fb80-61e9-11ea-9614-b29f61e2642b.png)

This ensures that files that are no longer present in the package/artifact being deployed are removed from the server.

More info here: [https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-rm-web-app-deployment?view=azure-devops#usage-notes](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-rm-web-app-deployment?view=azure-devops#usage-notes)
